LOCK TABLES poc_legacy.patients WRITE;
update poc_legacy.patients set address_1 = '10 Swinnow View', address_2 = 'Leeds',  address_3 ='', postcode ='LS13 4EL' where id =     1;
update poc_legacy.patients set address_1 = '13 Oxford Rd', address_2 = 'Halifax',  address_3 ='', postcode ='HX1 2QU ' where id =        2;
update poc_legacy.patients set address_1 = '23 Ramshead Approach', address_2 = 'Leeds',  address_3 ='', postcode ='LS14 1HH' where id =       3;
update poc_legacy.patients set address_1 = '16A Grove Ln', address_2 = 'Leeds',  address_3 ='', postcode ='LS6 2AP ' where id =   4;
update poc_legacy.patients set address_1 = '17 N Parade', address_2 = 'Ilkley',  address_3 ='', postcode ='LS29 8JN' where id =     5;
update poc_legacy.patients set address_1 = '11 Bedford Garth', address_2 = 'Leeds',  address_3 ='', postcode ='LS16 6DW' where id =  6;
update poc_legacy.patients set address_1 = '4 Shearing Cross Gardens', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD1 6JZ ' where id =    7;
update poc_legacy.patients set address_1 = '2 Limewood Rd', address_2 = 'Leeds',  address_3 ='', postcode ='LS14 1LU' where id =     8;
update poc_legacy.patients set address_1 = '1 Suffolk Rise', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD2 1ZG ' where id =     9;
update poc_legacy.patients set address_1 = '5 Milner Pl', address_2 = 'Luddenden Foot',  address_3 ='', postcode ='HX2 6AE ' where id =     10;
update poc_legacy.patients set address_1 = '177 Town St', address_2 = 'Leeds',  address_3 ='', postcode ='LS10 3SN' where id =      11;
update poc_legacy.patients set address_1 = '19 Phoebe Ln', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 9EX ' where id =   12;
update poc_legacy.patients set address_1 = 'Hebble End', address_2 = 'Hebden Bridge',  address_3 ='', postcode ='HX7 8EE ' where id =   13;
update poc_legacy.patients set address_1 = '93 Marsh Ln, Shepley', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD8 8AP ' where id =    14;
update poc_legacy.patients set address_1 = '2 Portman St, Calverley', address_2 = 'Pudsey',  address_3 ='', postcode ='LS28 5PG' where id =         15;
update poc_legacy.patients set address_1 = '13 Gratrix Ln', address_2 = 'Sowerby Bridge',  address_3 ='', postcode ='HX6 2PX ' where id =    16;
update poc_legacy.patients set address_1 = '31 Savile St, Emley', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD8 9RX ' where id =   17;
update poc_legacy.patients set address_1 = '14 Oakdean', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD2 2FA ' where id =   18;
update poc_legacy.patients set address_1 = '31 Lisbon St', address_2 = 'Leeds',  address_3 ='', postcode ='LS1 4LX ' where id =   19;
update poc_legacy.patients set address_1 = 'Oak Park Dr', address_2 = 'Leeds',  address_3 ='', postcode ='LS16 6RW' where id =20;
update poc_legacy.patients set address_1 = '11 Farm Hill Mews, Morley', address_2 = 'Leeds',  address_3 ='', postcode ='LS27 9RR' where id =     21;
update poc_legacy.patients set address_1 = '25 Plantation Gardens', address_2 = 'Leeds',  address_3 ='', postcode ='LS17 8SX' where id =    22;
update poc_legacy.patients set address_1 = '4 Netherfield Rise, Guiseley', address_2 = 'Leeds',  address_3 ='', postcode ='LS20 9HG' where id =    23;
update poc_legacy.patients set address_1 = '56 Spa Field Terrace, Slaithwaite', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD7 5BE ' where id =        24;
update poc_legacy.patients set address_1 = '1 High St', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD1 2LT ' where id =   25;
update poc_legacy.patients set address_1 = '46 Crowtrees Ln', address_2 = 'Brighouse',  address_3 ='', postcode ='HD6 3NH ' where id =       26;
update poc_legacy.patients set address_1 = '6 Exley Gardens', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 9EF ' where id =    27;
update poc_legacy.patients set address_1 = '3 The Haywain, Lower Constable Rd', address_2 = 'Ilkley',  address_3 ='', postcode ='LS29 8SL' where id =   28;
update poc_legacy.patients set address_1 = '159 Woodhouse Ln', address_2 = 'Leeds',  address_3 ='', postcode ='LS2 3ED ' where id =      29;
update poc_legacy.patients set address_1 = '5 Lambton Pl', address_2 = 'Leeds',  address_3 ='', postcode ='LS8 5PF ' where id =30;
update poc_legacy.patients set address_1 = 'Amelia Stewart Lane', address_2 = 'Leeds',  address_3 ='', postcode ='LS15 8HY' where id =     31;
update poc_legacy.patients set address_1 = 'Netherfield Rd, Guiseley', address_2 = 'Leeds',  address_3 ='', postcode ='LS20 7LP' where id =       32;
update poc_legacy.patients set address_1 = '19 Bowman Terrace', address_2 = 'Halifax',  address_3 ='', postcode ='HX1 5PB ' where id =     33;
update poc_legacy.patients set address_1 = '2 Henconner Rd', address_2 = 'Leeds',  address_3 ='', postcode ='LS7 3NU ' where id = 34;
update poc_legacy.patients set address_1 = '1 York St', address_2 = 'Hebden Bridge',  address_3 ='', postcode ='HX7 6HZ ' where id =   35;
update poc_legacy.patients set address_1 = '3 Lenton Dr', address_2 = 'Leeds',  address_3 ='', postcode ='LS11 5JW' where id =       36;
update poc_legacy.patients set address_1 = '5 Cotton St', address_2 = 'Leeds',  address_3 ='', postcode ='LS9 8BR ' where id =    37;
update poc_legacy.patients set address_1 = '63 New Rd', address_2 = 'Holmfirth',  address_3 ='', postcode ='HD9 3XY ' where id =    38;
update poc_legacy.patients set address_1 = '3 Mulberry Garth, Thorp Arch', address_2 = 'Wetherby',  address_3 ='', postcode ='LS23 7AF' where id =     39;
update poc_legacy.patients set address_1 = '24 Kenilworth Dr', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 8XP ' where id = 40;
update poc_legacy.patients set address_1 = '6 Portage Ave', address_2 = 'Leeds',  address_3 ='', postcode ='LS15 0DY' where id = 41;
update poc_legacy.patients set address_1 = '9 Barrowby Cl, Menston', address_2 = 'Ilkley',  address_3 ='', postcode ='LS29 6EA' where id =    42;
update poc_legacy.patients set address_1 = '1 Grange Terrace, Marsden', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD7 6AH ' where id =      43;
update poc_legacy.patients set address_1 = '1 Brow Wood Rise', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 7QN ' where id =          44;
update poc_legacy.patients set address_1 = '10 Croft House Ct', address_2 = 'Pudsey',  address_3 ='', postcode ='LS28 7NN' where id =   45;
update poc_legacy.patients set address_1 = '1 Green End', address_2 = 'Hebden Bridge',  address_3 ='', postcode ='HX7 8SQ ' where id =  46;
update poc_legacy.patients set address_1 = '23 Moor Park Ave', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD4 7A  ' where id =    47;
update poc_legacy.patients set address_1 = '142 Gramfield Rd', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD4 5QE ' where id =    48;
update poc_legacy.patients set address_1 = '3 Field Head Ln', address_2 = 'Halifax',  address_3 ='', postcode ='HX2 9J  ' where id =      49;
update poc_legacy.patients set address_1 = '3 Ely St', address_2 = 'Leeds',  address_3 ='', postcode ='LS12 2NJ' where id =     50;
update poc_legacy.patients set address_1 = '8 Spring Terrace, New Bank', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 6AD ' where id =      51;
update poc_legacy.patients set address_1 = '718 Manchester Rd', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD4 5SP ' where id = 52;
update poc_legacy.patients set address_1 = '23 Arthington Grove', address_2 = 'Leeds',  address_3 ='', postcode ='LS10 2NE' where id =      53;
update poc_legacy.patients set address_1 = '3 South View, Town Rd', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD5 0HN ' where id =      54;
update poc_legacy.patients set address_1 = '20A Old Marsh', address_2 = 'Sowerby Bridge',  address_3 ='', postcode ='HX6 2JF ' where id =      55;
update poc_legacy.patients set address_1 = '1 Milton Terrace', address_2 = 'Leeds',  address_3 ='', postcode ='LS5 3JA ' where id =   56;
update poc_legacy.patients set address_1 = '4 Park Spring Rise', address_2 = 'Leeds',  address_3 ='', postcode ='LS13 4DU' where id =  57;
update poc_legacy.patients set address_1 = '16 Green Balk Ln, Lepton', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD8 0EW ' where id =  58;
update poc_legacy.patients set address_1 = '170 Roundway, Honley', address_2 = 'Holmfirth',  address_3 ='', postcode ='HD9 6DG ' where id =    59;
update poc_legacy.patients set address_1 = '8 The Ct, The Ln', address_2 = 'Leeds',  address_3 ='', postcode ='LS17 7DT' where id =     60;
update poc_legacy.patients set address_1 = '1 Horsehold Ln,'	, address_2 = 'Hebden Bridge',  address_3 ='', postcode ='HX7 6JN ' where id =     61;
update poc_legacy.patients set address_1 = '11 Albany Walk', address_2 = 'Ilkley',  address_3 ='', postcode ='LS29 9LZ' where id =  62;
update poc_legacy.patients set address_1 = '51 Church Ln, South Crosland', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD4 7DD ' where id =      63;
update poc_legacy.patients set address_1 = '33 Crestfield Cres', address_2 = 'Elland',  address_3 ='', postcode ='HX5 0LS ' where id =  64;
update poc_legacy.patients set address_1 = '1 Oakwood Terrace', address_2 = 'Pudsey',  address_3 ='', postcode ='LS28 8NY' where id =      65;
update poc_legacy.patients set address_1 = '9 Simpson Rd, Mytholmroyd', address_2 = 'Hebden Bridge',  address_3 ='', postcode ='HX7 5BB ' where id =66;
update poc_legacy.patients set address_1 = '9 Holt Way', address_2 = 'Leeds',  address_3 ='', postcode ='LS16 7QP' where id =      67;
update poc_legacy.patients set address_1 = '35 Pinfold Ln, Methley', address_2 = 'Leeds',  address_3 ='', postcode ='LS26 9AA' where id = 68;
update poc_legacy.patients set address_1 = '9 Holme Dr', address_2 = 'Halifax',  address_3 ='', postcode ='HX2 7RT ' where id =     69;
update poc_legacy.patients set address_1 = '43 Wetherby Rd', address_2 = 'Tadcaster',  address_3 ='', postcode ='LS24 9JW' where id =          70;
update poc_legacy.patients set address_1 = '6 Hubert St', address_2 = 'Halifax',  address_3 ='', postcode ='HX2 0AS ' where id =   71;
update poc_legacy.patients set address_1 = '10 Turkey Hill', address_2 = 'Pudsey',  address_3 ='', postcode ='LS28 9HE' where id =    72;
update poc_legacy.patients set address_1 = '145 Main St, Burley in Wharfedale', address_2 = 'Ilkley',  address_3 ='', postcode ='LS29 7JE' where id =      73;
update poc_legacy.patients set address_1 = '1-10 Holybrook Ct, Holywell Green', address_2 = 'Halifax',  address_3 ='', postcode ='HX4 9BW ' where id =     74;
update poc_legacy.patients set address_1 = '41 Eaton Hill', address_2 = 'Leeds',  address_3 ='', postcode ='LS16 6SE' where id =      75;
update poc_legacy.patients set address_1 = '3 Aysgarth Rd', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD4 6QY ' where id =       76;
update poc_legacy.patients set address_1 = '9 Manor Ln, Oulton', address_2 = 'Leeds',  address_3 ='', postcode ='LS26 8JB' where id =      77;
update poc_legacy.patients set address_1 = '3 Lea View, Horsforth', address_2 = 'Leeds',  address_3 ='', postcode ='LS18 5BW' where id =       78;
update poc_legacy.patients set address_1 = '9 Belle Vue Terrace, Guiseley', address_2 = 'Leeds',  address_3 ='', postcode ='LS20 9BU' where id =     79;
update poc_legacy.patients set address_1 = '10 Primrose Way', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 7RR ' where id =    80;
update poc_legacy.patients set address_1 = '98 Kirkstall Rd', address_2 = 'Leeds',  address_3 ='', postcode ='LS3 1YN ' where id =      81;
update poc_legacy.patients set address_1 = '91 Kendal Dr', address_2 = 'Leeds',  address_3 ='', postcode ='LS15 0BA' where id = 82;
update poc_legacy.patients set address_1 = '25 Upper Sunny Bank Mews, Meltham', address_2 = 'Holmfirth',  address_3 ='', postcode ='HD9 5AA ' where id =  83;
update poc_legacy.patients set address_1 = '5A Burley St', address_2 = 'Leeds',  address_3 ='', postcode ='LS3 1LD ' where id =       84;
update poc_legacy.patients set address_1 = '7 Cross St W', address_2 = 'Halifax',  address_3 ='', postcode ='HX2 0HA ' where id =  85;
update poc_legacy.patients set address_1 = '1 Limewood Rd', address_2 = 'Leeds',  address_3 ='', postcode ='LS14 1AB' where id =      86;
update poc_legacy.patients set address_1 = 'Dalton Grange', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD5 9PT ' where id =    87;
update poc_legacy.patients set address_1 = '19 Lea Farm Rd', address_2 = 'Leeds',  address_3 ='', postcode ='LS5 3PB ' where id =       88;
update poc_legacy.patients set address_1 = '9 Bridge Garth, Clifford', address_2 = 'Wetherby',  address_3 ='', postcode ='LS23 6HF' where id =   89;
update poc_legacy.patients set address_1 = '2 Burlington St', address_2 = 'Halifax',  address_3 ='', postcode ='HX1 4NR ' where id =     90;
update poc_legacy.patients set address_1 = '4 School St', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD5 8AU ' where id = 91;
update poc_legacy.patients set address_1 = '59 Gib Ln, Skelmanthorpe', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD8 7LL ' where id =  92;
update poc_legacy.patients set address_1 = '20 Winding Way', address_2 = 'Leeds',  address_3 ='', postcode ='LS17 7RA' where id =     93;
update poc_legacy.patients set address_1 = '36 Watroyd Ln, Golcar', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD7 4LB ' where id =     94;
update poc_legacy.patients set address_1 = '14 Batley Ave', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD1 4NA ' where id =    95;
update poc_legacy.patients set address_1 = '57 Steep Bank Side', address_2 = 'Halifax',  address_3 ='', postcode ='HX3 9PX ' where id =      96;
update poc_legacy.patients set address_1 = '8 Orchard Cl, South Milford', address_2 = 'Leeds',  address_3 ='', postcode ='LS25 5BQ' where id =     97;
update poc_legacy.patients set address_1 = '32 Barrowby Ln', address_2 = 'Leeds',  address_3 ='', postcode ='LS15 8QE' where id =    98;
update poc_legacy.patients set address_1 = '38 Wood Ln', address_2 = 'Huddersfield',  address_3 ='', postcode ='HD4 6PU' where id =   99;
UNLOCK TABLES;